import { DEFAULT_COIN_AMOUNT, DEFAULT_LANGUAGE, DEFAULT_CURRENCY } from "../../../constants/config";

export const userModel = {
    id: null,
    email: null,
    emailVerified: false,
    password: null,
    displayName: null,
    fortuneHistoryIds: [],
    transactionIds: [], 
    referralIds: [],
    referralCode: Math.random().toString(36).substring(2,8).toUpperCase(),
    adViews: 0,
    lastFortuneTime: null,
    lastLogin: '',
    createdAt: '',
    updatedAt: '',
    coinAmount: DEFAULT_COIN_AMOUNT,
    age: null,
    maritalStatus: null,
    jobStatus: null,
    education: null,
    language: DEFAULT_LANGUAGE,
    currency: DEFAULT_CURRENCY,
}