export const userModel = {
    id: null,
    email: null,
    emailVerified: false,
    password: null,
    displayName: null,
    fortuneHistoryIds: [],
    transactionIds: [], 
    referralIds: [],
    referralCode: Math.random().toString(36).substring(2,8).toUpperCase(),
    adViews: 0,
    lastFortuneTime: null,
    lastLogin: '',
    createdAt: '',
    updatedAt: '',
    coinAmount: 3,
    age: null,
    maritalStatus: null,
    jobStatus: null,
    education: null,
    language: "Turkish",
    currency: "TRY",
}